lang: zh-Hans
url: https://nshipster.cn

title: NSHipster
description: "<strong>NSHipster</strong> 关注被忽略的 Objective-C、Swift 和 Cocoa 特性。每周更新。"
permalink: /:title/
timezone: Asia/Shanghai
lsi: false

markdown: kramdown
highlighter: rouge

include:
  - .well-known

exclude:
  - articles/
  - books/
  - training/
  - Gemfile*
  - Procfile
  - Rakefile
  - rakelib/
  - netlify.toml

groups:
  - Cocoa
  - Objective-C
  - Swift
  - Open Source
  - Xcode
  - Miscellanea

collections:
  authors:
    output: true
    permalink: /authors/:path/
  translators:
    output: true
    permalink: /translators/:path/
  books:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "translators"
    values:
      layout: "translator"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

